### PR TITLE
install script contains bad file paths

### PR DESCRIPTION
**Pull request by zfasel**
Guide at https://www.duosecurity.com/docs/jira doesn't reference this install script like the confluence walk-through and contains references to non-existent files in this package. 

Since walk through doesn't make mention to this script, i suggest removal of this script (or, you know, updating the doc and the install script to be more parallel to the confluence install)

### CODE REVIEW

**Comment by zfasel** [comment]
Going through things and added 2 more items

1) Made pretty by adding the meta header (similar to https://github.com/duosecurity/duo_confluence/pull/4 pretty-fying)

2) Fixed issue with context being double-added to "duo.originalurl.key" - too tired to trace it now, but actionArg seems to be getting double-contexts added. Example, for /jira, it became:

    'post_action': "\/jira\/plugins\/servlet\/duologin?duo.originalurl.key=\/jira%2Fjira%2Fdefault.jsp"

**Comment by BradleyHiggins** [comment]
Thanks for bringing this to our attention!  We'll update the docs and the install script to refer to the updated .jar's.

We'll take a look at your other updates, too.

Thanks for using Duo!

**Comment by BradleyHiggins** [comment]
We've updated install.sh fix and fixed the docs.

I believe the actionArg issue you've run into is due to the modification to TwoFactorLoginServlet.java made in https://github.com/zfasel/duo_confluence/commit/0ef4be269a604c06a0fd2e62dfd1ad19aa2bc4fa.  I think the fix is to remove that change, rather than to make the proposed actionArg modification here.

**Comment by zfasel** [comment]
@BradleyHiggins Not related to https://github.com/zfasel/duo_confluence/commit/0ef4be269a604c06a0fd2e62dfd1ad19aa2bc4fa at all. Kept the trees completely separate when testing as well as this occurs even with an install of the pre-compiled duo-twofactor-1.3.1-SNAPSHOT.jar

I'll be submitting an update to the pull for https://github.com/zfasel/duo_confluence/commit/0ef4be269a604c06a0fd2e62dfd1ad19aa2bc4fa though as it seems it's an issue affecting it too if https://domain.tld/confluence/login.action has os_destination set for anything (example is %2Fusers%2Fviewuserprofile.action%3Fusername%3Duser)

**Comment by erikbarbara** [comment]
@zfasel, thanks again for pointing out the non-root context issue. I just pushed a commit that fixes the issue. I didn't pull in your page decorator UI change. We try to keep the duologin.vm bare bones and allow users to perform custom changes as described in our docs: https://www.duosecurity.com/docs/confluence#appendix-building-manually

Thanks again for using Duo!

**Pull request closed without merging**
